# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'WolfVideo' do
  # use_frameworks!
    pod 'IQKeyboardManager'

  target 'WolfVideo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WolfVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
